/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        brand: {
          25:  '#f2f7ff',
          50:  '#ecf3ff',
          100: '#dde9ff',
          200: '#c2d6ff',
          300: '#9cb9ff',
          400: '#7592ff',
          500: '#465fff',
          600: '#3641f5',
          700: '#2a31d8',
          800: '#252dae',
          900: '#262e89',
          950: '#161950',
        },
        'deep-ocean':               '#002147',
        'tropical-sun':             '#FFC107',
        'sand-beige':               '#F4F1EA',
        'lush-green':               '#2D5A27',
        'surface':                  '#f8f9fa',
        'surface-bright':           '#f8f9fa',
        'surface-dim':              '#d9dadb',
        'surface-variant':          '#e1e3e4',
        'surface-container':        '#edeeef',
        'surface-container-low':    '#f3f4f5',
        'surface-container-high':   '#e7e8e9',
        'surface-container-highest':'#e1e3e4',
        'surface-container-lowest': '#ffffff',
        'on-surface':               '#191c1d',
        'on-surface-variant':       '#43474f',
        'on-primary':               '#ffffff',
        'primary':                  '#001e40',
        'primary-container':        '#003366',
        'primary-fixed':            '#d5e3ff',
        'inverse-primary':          '#a7c8ff',
        'secondary-container':      '#fcd400',
        'error-container':          '#ffdad6',
      },
      fontFamily: {
        'display-lg':        ['"Playfair Display"', 'Georgia', 'serif'],
        'display-lg-mobile': ['"Playfair Display"', 'Georgia', 'serif'],
        'headline-lg':       ['"Playfair Display"', 'Georgia', 'serif'],
        'headline-md':       ['"Playfair Display"', 'Georgia', 'serif'],
        'body-lg':           ['Montserrat', 'system-ui', 'sans-serif'],
        'body-md':           ['Montserrat', 'system-ui', 'sans-serif'],
        'label-lg':          ['Montserrat', 'system-ui', 'sans-serif'],
        'label-sm':          ['Montserrat', 'system-ui', 'sans-serif'],
        sans:                ['Montserrat', 'system-ui', 'sans-serif'],
        serif:               ['"Playfair Display"', 'Georgia', 'serif'],
      },
      fontSize: {
        'display-lg':        ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['40px', { lineHeight: '48px', fontWeight: '700' }],
        'headline-lg':       ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-md':       ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg':           ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md':           ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-lg':          ['14px', { lineHeight: '20px', letterSpacing: '0.1em', fontWeight: '600' }],
        'label-sm':          ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      spacing: {
        'gutter':         '24px',
        'margin-mobile':  '16px',
        'margin-desktop': '64px',
        'section-gap':    '120px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg:      '0.75rem',
        xl:      '1rem',
        '2xl':   '1.5rem',
        '3xl':   '2rem',
        full:    '9999px',
      },
    },
  },
  plugins: [],
}
